name: spotify_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#000000"
  image: assets/images/Spotify_Logo.png
  android: true
  ios: true

  android_12:
    color: "#000000"
    image: assets/images/Spotify_Logo.png
    icon_background_color: "#000000"
    image_dark: assets/images/Spotify_Logo.png
    icon_background_color_dark: "#000000"
    branding: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/
